# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build and Deploy

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      node-version: 17.x
      branch: ${{ github.ref_name }}

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ env.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.node-version }}
          cache: 'yarn'
      - run: yarn install --immutable --immutable-cache
      - run: yarn run build
      - run: |
          git status
          git config user.name "Action Runner"
          git add docs
          git commit -m "Rebuild application"
          git push
